dist: xenial
sudo: required

language: c

matrix:
  fast_finish: true

addons:
  apt:
    packages:
      - perl
      - cmake
      - check
      - lua-check
      - automake
      - autoconf
      - cpanminus
      - pkg-config
      - build-essential
      - libncurses5-dev
      - libpcre3
      - libpcre3-dev
      - libreadline-dev
      - libssl-dev
      - libjemalloc-dev
      - libjemalloc1
      - libtool

services:
  - mysql

before_install:
  - $PWD/.travis/linux_runner.sh before_install

install:
  - $PWD/.travis/linux_runner.sh do_install

script:
  - $PWD/.travis/linux_runner.sh run_tests
